"""Generate ninth-game exact/key UI dictionaries for the display-only runtime."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path


GAME = Path(__file__).resolve().parents[1]
INPUTS = ("ui-localization.zh-CN.json", "shell-ui-localization.zh-CN.json")


def generate():
    exact: dict[str, str] = {}
    keys: dict[str, str] = {}
    hashes: list[str] = []

    def add(table: dict[str, str], source: str, target: str) -> None:
        if not source or not target:
            raise ValueError("Empty UI source/target")
        if source in table and table[source] != target:
            raise ValueError("Conflicting UI translation: " + source)
        table[source] = target

    for name in INPUTS:
        raw = (GAME / "work" / name).read_bytes()
        hashes.append(f"{name}: {hashlib.sha256(raw).hexdigest()}")
        document = json.loads(raw.decode("utf-8-sig"))
        for entry in document["entries"]:
            source = entry["source"]
            target = entry["target"]
            add(exact, source, target)
            if "\r\n" in source:
                add(exact, source.replace("\r\n", "\n"), target.replace("\r\n", "\n"))
            key = entry.get("key")
            if key:
                add(keys, key, target.replace("\r\n", "\n") if "\r\n" not in source else target)

    def dictionary(name: str, entries: dict[str, str]) -> str:
        lines = [
            f"        internal static readonly Dictionary<string, string> {name}",
            "            = new Dictionary<string, string>(StringComparer.Ordinal)",
            "        {",
        ]
        for source, target in sorted(entries.items()):
            lines.append(
                "            { "
                + json.dumps(source, ensure_ascii=False)
                + ", "
                + json.dumps(target, ensure_ascii=False)
                + " },"
            )
        return "\n".join(lines + ["        };"])

    result = (
        "// Generated by scripts/generate_ui_data.py. Do not edit by hand.\n"
        + "\n".join("// " + value for value in hashes)
        + "\nusing System;\nusing System.Collections.Generic;\n\nnamespace Kibu9ZhCN\n{\n"
        + "    internal static class UiLocalizationData\n    {\n"
        + dictionary("Exact", exact)
        + "\n"
        + dictionary("Keys", keys)
        + "\n    }\n}\n"
    )
    destination = GAME / "bepinex" / "src" / "UiLocalizationData.cs"
    destination.write_text(result, encoding="utf-8")
    print(f"UI dictionaries: {len(exact)} exact display strings, {len(keys)} localization keys; {destination}")
    return exact, keys


if __name__ == "__main__":
    generate()
