// Generated by scripts/generate_ui_data.py. Do not edit by hand.
// ui-localization.zh-CN.json: f6c240434f0a7e16256e8d94339758ff88a81400cd9d497e012a518128ae3662
// shell-ui-localization.zh-CN.json: 3d46529c9b8be50a202c54a77165762653ae4c9327bc57b25ac7d6333391ba7a
using System;
using System.Collections.Generic;

namespace Kibu9ZhCN
{
    internal static class UiLocalizationData
    {
        internal static readonly Dictionary<string, string> Exact
            = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "Loading...", "加载中……" },
            { "■　データ確認中…　■", "■　正在检查数据……　■" },
            { "「{0}」で宜しいですか？", "确定使用“{0}”吗？" },
            { "あそびかた", "玩法说明" },
            { "いいえ", "否" },
            { "されていません。　", "尚未注册。　" },
            { "しました。", "失败。" },
            { "はい", "是" },
            { "ウィンドウ設定", "窗口设置" },
            { "ゲームを終了しますか？", "要退出游戏吗？" },
            { "ゲームを終了する", "退出游戏" },
            { "ゲームランチに登録", "游戏午餐服务" },
            { "ジャンル：推理アドベンチャー\n淡い鈍色の空に、彼の面影を追う…。\n8年前の癸生川探偵事務所、もうひとりの名探偵。", "类型：推理冒险\n在淡淡的铅灰天空下，追寻他的身影……\n八年前的癸生川侦探事务所，另一位名侦探。" },
            { "ジャンル：推理アドベンチャー\r\n淡い鈍色の空に、彼の面影を追う…。\r\n8年前の癸生川探偵事務所、もうひとりの名探偵。", "类型：推理冒险\r\n在淡淡的铅灰天空下，追寻他的身影……\r\n八年前的癸生川侦探事务所，另一位名侦探。" },
            { "タイトルに戻る", "返回标题画面" },
            { "タイトル画面に戻りますか？", "要返回标题画面吗？" },
            { "ダウンロードに失敗", "下载" },
            { "ダウンロード成功", "下载成功" },
            { "データ展開中", "正在解压数据" },
            { "ネットワークから切断されました", "网络连接已断开" },
            { "ネットワークの接続に", "网络连接" },
            { "フィルタ", "滤镜" },
            { "フルスクリーン", "全屏" },
            { "フレーム", "边框" },
            { "プレイヤー名", "玩家名称" },
            { "ランキング", "排行榜" },
            { "ランキングを取得する", "获取排行榜" },
            { "ランク外", "未上榜" },
            { "入力して下さい", "请输入" },
            { "再度起動してください。", "请重新启动。" },
            { "削除", "删除" },
            { "失敗しました｡ 　　　", "失败。　　　" },
            { "戻る", "返回" },
            { "探偵・癸生川凌介事件譚\nVol.9「五月雨は鈍色の調べ」", "侦探·癸生川凌介事件谭\nVol.9《五月雨是铅灰的旋律》" },
            { "探偵・癸生川凌介事件譚\r\nVol.9「五月雨は鈍色の調べ」", "侦探·癸生川凌介事件谭\r\nVol.9《五月雨是铅灰的旋律》" },
            { "操作説明", "操作说明" },
            { "文字装飾あり", "文字装饰：开" },
            { "文字装飾なし", "文字装饰：关" },
            { "本ゲームはオートセーブに対応しておりません。\n終了する際は、ゲーム内のセーブ機能をご利用ください。", "本游戏不支持自动存档。\n退出时，请使用游戏内的存档功能。" },
            { "本ゲームはオートセーブに対応しておりません。\r\n終了する際は、ゲーム内のセーブ機能をご利用ください。", "本游戏不支持自动存档。\r\n退出时，请使用游戏内的存档功能。" },
            { "決定", "确定" },
            { "画像ダウンロード", "下载图像" },
            { "移動中や電波が弱い場合", "移动中或信号较弱时，" },
            { "終了", "退出" },
            { "課金チェック中…", "正在检查购买状态……" },
            { "起こりやすい現象です。", "容易出现这种情况。" },
            { "閉じる", "关闭" },
            { "音楽ダウンロード", "下载音乐" },
            { "＜ゲーム画面＞", "＜游戏画面＞" },
        };
        internal static readonly Dictionary<string, string> Keys
            = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "common_dialog_disconnected_msg", "网络连接已断开" },
            { "common_dialog_exit_game_msg", "要退出游戏吗？" },
            { "common_dialog_no_label", "否" },
            { "common_dialog_titlescreen_msg", "要返回标题画面吗？" },
            { "common_dialog_yes_label", "是" },
            { "loading_autosave_msg", "本游戏不支持自动存档。\n退出时，请使用游戏内的存档功能。" },
            { "pause_menu_label_backtitle", "返回标题画面" },
            { "pause_menu_label_close", "关闭" },
            { "pause_menu_label_filter", "滤镜" },
            { "pause_menu_label_frame", "边框" },
            { "pause_menu_label_howtoplay", "玩法说明" },
            { "pause_menu_label_ranking", "排行榜" },
            { "ranking_get_ranking_msg", "获取排行榜" },
            { "ranking_load_ranking_msg", "加载中……" },
            { "ranking_unranked_label", "未上榜" },
        };
    }
}
