"""Generate only eighth-game in-memory UI dictionaries; never changes game assets."""
import hashlib
import json
from pathlib import Path

GAME = Path(__file__).resolve().parents[1]
INPUTS = ["ui-localization.zh-CN.json", "ui-assembly.zh-CN.json", "ui-serialized.zh-CN.json"]
ALLOWED = {"player_ui", "legacy_service_ui", "player_ui_serialized",
           "existing_localization_duplicate", "existing_assembly_duplicate"}
SENTINELS = {"停止", "消去", "全", "変えないでお願いします", "ＦＯ", "漢字"}


def generate():
    exact, keys, hashes = {}, {}, []

    def add(table, source, target):
        if not source or not isinstance(target, str) or not target:
            raise ValueError("Empty UI source/target")
        if source in SENTINELS:
            raise ValueError("Technical sentinel cannot enter display catalog: " + source)
        if source in table and table[source] != target:
            raise ValueError("Conflicting UI translation: " + source)
        table[source] = target

    for name in INPUTS:
        raw = (GAME / "work" / name).read_bytes()
        hashes.append(name + ": " + hashlib.sha256(raw).hexdigest())
        document = json.loads(raw.decode("utf-8-sig"))
        for entry in document["entries"]:
            if entry["classification"] not in ALLOWED:
                continue
            source, target = entry["source_text"], entry["target_text"]
            # Match the source's newline convention; CSV targets can retain CRLF
            # even when their Japanese column was normalized by extraction.
            if "\r\n" not in source:
                target = target.replace("\r\n", "\n")
            add(exact, source, target)
            # Text/CSV readers can normalize CRLF. Both are guarded full strings.
            if "\r\n" in source:
                add(exact, source.replace("\r\n", "\n"), target.replace("\r\n", "\n"))
            if name == INPUTS[0]:
                add(keys, entry["key"], target)

    def dictionary(name, entries):
        lines = ["        internal static readonly Dictionary<string, string> " + name,
                 "            = new Dictionary<string, string>(StringComparer.Ordinal)", "        {"]
        for source, target in sorted(entries.items()):
            lines.append("            { " + json.dumps(source, ensure_ascii=False) + ", "
                         + json.dumps(target, ensure_ascii=False) + " },")
        return "\n".join(lines + ["        };"])

    result = ("// Generated by scripts/generate_ui_data.py. Do not edit by hand.\n"
              + "\n".join("// " + value for value in hashes)
              + "\nusing System;\nusing System.Collections.Generic;\n\nnamespace Kibu8ZhCN\n{\n"
              + "    internal static class UiLocalizationData\n    {\n"
              + dictionary("Exact", exact) + "\n" + dictionary("Keys", keys)
              + "\n    }\n}\n")
    destination = GAME / "bepinex/src/UiLocalizationData.cs"
    destination.write_text(result, encoding="utf-8")
    print("UI dictionaries: %d exact display strings, %d localization keys; %s" %
          (len(exact), len(keys), destination))
    return exact, keys


if __name__ == "__main__":
    generate()
