[package]
name = "kibukawa-web-spinoffs"
version = "0.1.0"
description = "癸生川网页番外汉化桌面启动器"
authors = ["Kibukawa CHS Project"]
edition = "2021"

[lib]
name = "kibukawa_web_spinoffs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
percent-encoding = "2"
tauri = { version = "2", features = [] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
